@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Nov 07 16:11:02 -0500 2024
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Control_Unit_tb_behav -key {Behavioral:dataPathTests:Functional:Control_Unit_tb} -tclbatch Control_Unit_tb.tcl -view C:/Users/dusti/Documents/EGRE426/16BitCPU/16BitCPU/ALUTB_behav.wcfg -log simulate.log"
call xsim  Control_Unit_tb_behav -key {Behavioral:dataPathTests:Functional:Control_Unit_tb} -tclbatch Control_Unit_tb.tcl -view C:/Users/dusti/Documents/EGRE426/16BitCPU/16BitCPU/ALUTB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
